site_name: Self Learning Journey
repo_url: https://github.com/xiong-ZH-zq/Self-Learning-Journey
repo_name: Self Learning Journey
theme:
  language: zh
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
  features:
    - navigation.tabs
    - navigation.path
  font:
    text: PT Serif

markdown_extensions:
  - meta
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.arithmatex:
        generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - callouts
  - tags
  - blog:
      enabled: true
      blog_dir: ./blog 
      blog_toc: true
      post_date_format: full
      post_dir: "{blog}/articles"
      categories: true
      categories_name: Categories
      archive_name: "归档"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
extra_javascript:
  - javascripts/katex.js 
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
extra_css:
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra: 
  attachments: "assets"
